# 什么是PyTorch？

PyTorch是一个基于Python的科学计算包，它适用于以下两种情况：

- 用于替代Numpy以能使用GPU资源
- 它是一个深度学习研究平台，并且拥有很强的灵活性和速度

# PyTorch简介

## Tensors（张量）

Tensors和Numpy中的ndarray非常相似，但是它能够额外使用GPU的资源来加速运算.

In [1]:
import torch

创建一个未初始化的$5\times3$矩阵：

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[5.7858e-39, 8.4490e-39, 5.3266e-39],
        [1.0010e-38, 9.0919e-39, 9.6429e-39],
        [9.2755e-39, 9.2755e-39, 1.0469e-38],
        [9.6429e-39, 9.4592e-39, 1.0561e-38],
        [1.0653e-38, 1.0286e-38, 1.0286e-38]])


创建一个随机初始化的矩阵：

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9987, 0.9303, 0.6265],
        [0.4073, 0.6494, 0.4091],
        [0.5698, 0.1849, 0.7318],
        [0.6595, 0.0063, 0.0217],
        [0.0094, 0.7542, 0.7764]])


创建一个零填充的矩阵，且数据类型dtype为long：

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


从数据直接创建tensor：

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


也可以从一个已经存在的tensor创建一个新的tensor。这些方法会重用已有tensor的属性（比如dtype），当然在创建的时候也可更改：

In [6]:
x = x.new_ones(5,3, dtype=torch.double)     # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)  # override dtype!
print(x)                                    # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6362, -0.1042, -0.7082],
        [ 0.0681, -0.2158, -0.3136],
        [ 0.2644,  1.1826, -0.9417],
        [ 0.1053,  0.5682,  0.3610],
        [-2.2965,  0.4562,  0.2517]])


获得张量的大小（维度）信息：

In [7]:
print(x.size())

torch.Size([5, 3])


**注意**：`torch.Size` 是一个tuple，所以其支持所有的元组操作。

## 基本运算

PyTorch中有很多方法可以对tensor进行运算，首先来看看加法：

加法：语法1

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.3925, -0.0587,  0.2385],
        [ 0.3370,  0.4500,  0.1091],
        [ 0.9717,  1.3322, -0.7660],
        [ 0.1982,  0.6263,  0.7104],
        [-1.8272,  0.7368,  0.3406]])


加法：语法2

In [9]:
print(torch.add(x, y))

tensor([[ 1.3925, -0.0587,  0.2385],
        [ 0.3370,  0.4500,  0.1091],
        [ 0.9717,  1.3322, -0.7660],
        [ 0.1982,  0.6263,  0.7104],
        [-1.8272,  0.7368,  0.3406]])


加法：提供一个张量作为输出

In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.3925, -0.0587,  0.2385],
        [ 0.3370,  0.4500,  0.1091],
        [ 0.9717,  1.3322, -0.7660],
        [ 0.1982,  0.6263,  0.7104],
        [-1.8272,  0.7368,  0.3406]])


加法：原址加法，即更改原有的值

In [12]:
y.add_(x)
print(y)

tensor([[ 1.3925, -0.0587,  0.2385],
        [ 0.3370,  0.4500,  0.1091],
        [ 0.9717,  1.3322, -0.7660],
        [ 0.1982,  0.6263,  0.7104],
        [-1.8272,  0.7368,  0.3406]])


**注意**：任何对tensor进行修改的操作函数都以下划线`_`作为后缀，例如：`x.copy_(), x.t_()`，都会改变x。

你可以像使用Numpy数组那样对tensor进行索引：

In [13]:
print(x[:, 1])

tensor([-0.1042, -0.2158,  1.1826,  0.5682,  0.4562])


改变大小：你可以使用`torch.view`函数来改变tensor的形状和大小：

In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1 表示这个维度由其他维度推算出来
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果tensor只有一个元素，可使用`.item()`获取其值作为一个python数值：

In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0800])
1.0800163745880127


另外tensor还支持上百种运算，例如转置、切片、线性代数运算等等，可以查看完整的[列表](https://pytorch.org/docs/stable/torch.html)。

# 和Numpy互相转换

Tensor和numpy的转换非常方便快捷，但是需要注意的是Tensor和Numpy数组底层是共享同一块内存，所以更改其中一个会同时更改另一个。

## 将Tensor转换为Numpy数组

In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


改变其中一个会影响另一个：

In [22]:
a.add_(1)
print(a)
print(b)

b += 1
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]
tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]


## 将Numpy数组转换为Tensor

注意我们更改a的时候，b也发生了变化：

In [23]:
import numpy as np

In [24]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


除了`CharTensor`CPU上的所有`Tensor`都可以转换为numpy数组，并且能够转换回来。

---
# CUDA Tensors

使用`.to`方法，可以将张量移动到任何设备上，例如GPU。

In [26]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([2.0800], device='cuda:0')
tensor([2.0800], dtype=torch.float64)
